Traceback (most recent call last):
  File "/Users/rh/test_dir/3D_PoseEstimation/phase4_joined/train.py", line 252, in <module>
    model = train(batch_size,n_epochs,lr,device,run_name,resume=Resume)
  File "/Users/rh/test_dir/3D_PoseEstimation/phase4_joined/train.py", line 41, in train
    training_set = H36_dataset(num_cams=num_cameras, subjectp=subjects[0:2], is_train = True)
NameError: name 'H36_dataset' is not defined